name: CI
on:
  push:
    branches:
    - 'releases/**'
    - develop
env:
  VERSION: '2.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set version if in release branch
      if: ${{ github.ref != 'refs/heads/develop' }}
      run: echo "VERSION=${GITHUB_BRANCH##*/}" >> $GITHUB_ENV
      env: 
        GITHUB_BRANCH: ${{ github.ref }}
    - name: Display version install
      run: echo "Installing version ${VERSION}"
    - run: npm install
    - run: npm rebuild
    - run: npm run-script build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CDN_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CDN_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Deploy toolbox to S3 bucket
      run: aws s3 sync ./dist/ s3://cdn.brand.illinois.edu/toolkit/$VERSION --delete --acl bucket-owner-full-control
    - run: npm run-script create-test-html
    - name: Deploy examples to S3 bucket
      run: aws s3 sync ./var/full-site-deploy/ s3://cdn.brand.illinois.edu/toolkit/$VERSION/examples --delete --acl bucket-owner-full-control
    - name: Deploy static images in examples to S3 bucket
      run: aws s3 sync ./tests/_reference/ s3://cdn.brand.illinois.edu/toolkit/$VERSION/examples/static-images --acl bucket-owner-full-control
    - name: Invalidate Cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id E2VPGHCUOM84HO --paths "/toolkit/$VERSION*"

